require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'iQuiz' do
  config = use_native_modules!

  # Pods for iQuiz
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'iQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iQuizUITests' do
    # Pods for testing
  end

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end